### ISSUE TITLE
**Cards**

### ISSUE THREAD

**Issue by markmoser** [IlluminusLimited/PinsterApi#138]
Cards can be added to your board to track the progress of issues and pull requests. You can also add note cards, like this one!

**Comment by markmoser** [comment]
How to move this to another repo? @scytherswings

**Comment by scytherswings** [comment]
Check out in the bottom right hand corner of this view. There's a "Transfer issue" button

**Comment by markmoser** [comment]
I don't see it. Maybe it's a permissions thing?

**Comment by scytherswings** [comment]
Alright I'll change your access to see if that adds the button for you

**Comment by markmoser** [comment]
Yea, I see it now.

**Comment by markmoser** [comment]
Yea, I see it now.
